athlete_id: test-strength-v3
generated_date: '2025-12-18 19:57:26'
tier: ayahuasca
plan_weeks: 24
race:
  id: unbound_gravel_200
  name: Unbound 200
  date: '2026-06-07'
strength_frequency: 0
exercise_exclusions: []
equipment_tier: minimal
key_days: []
strength_days: []
