athlete_id: matti-rowe
generated_date: '2025-12-15 14:32:33'
tier: compete
plan_weeks: 21
race:
  id: unbound_gravel_200
  name: Unbound Gravel 200
  date: '2025-06-07'
strength_frequency: 2
exercise_exclusions:
- Jump Squat
- Box Jump
equipment_tier: moderate
key_days:
- monday
- tuesday
- thursday
- saturday
strength_days:
- saturday
- sunday
